name: be_english
description: "Application for learning English language, by Arturo Picazo"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  firebase_storage: ^11.7.4
  cloud_firestore: ^4.17.2
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  file_picker: ^8.0.3
  image_picker: ^1.1.1
  flutter_launcher_icons: ^0.13.1
  cached_network_image: ^3.3.1
  awesome_notifications: ^0.9.3+1
  just_audio: ^0.9.38


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/icon/notification_icon.png
    - assets/audio/extract1.mp3
    - assets/audio/extract2.mp3
    - assets/audio/extract3.mp3
    - assets/audio/part2.mp3
    - assets/audio/part3.mp3
    - assets/audio/part4.mp3

flutter_icons:
  android: true
  image_path: "assets/icon/icon.png"
