// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP_umNt04yYMQpLDFGm5vHSPZmI_3xKVM',
    appId: '1:868199958716:web:8d877f2a40050597a6e8b9',
    messagingSenderId: '868199958716',
    projectId: 'beenglish-c1cbb',
    authDomain: 'beenglish-c1cbb.firebaseapp.com',
    storageBucket: 'beenglish-c1cbb.appspot.com',
    measurementId: 'G-Q96T99LZLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPXcJQR2lDKQA9EbEaLVCw6Jan8allmw4',
    appId: '1:868199958716:android:d316f54a309c8480a6e8b9',
    messagingSenderId: '868199958716',
    projectId: 'beenglish-c1cbb',
    storageBucket: 'beenglish-c1cbb.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDP_umNt04yYMQpLDFGm5vHSPZmI_3xKVM',
    appId: '1:868199958716:web:a3d3eddf27096c64a6e8b9',
    messagingSenderId: '868199958716',
    projectId: 'beenglish-c1cbb',
    authDomain: 'beenglish-c1cbb.firebaseapp.com',
    storageBucket: 'beenglish-c1cbb.appspot.com',
    measurementId: 'G-QMNC64BBDH',
  );
}
